import './globals.css'

import Footer from '@/components/Footer/Footer'
import { Header } from '@/components/Header/Header'
import { poppins } from '@/assets/fonts'
export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <main className="container">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
